# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
modbus_host_ip: {modbus_host_ip}  # Update with the IP of your inverter. No default. Check the IP of your inverter!
modbus_port: 502  # Update with the Modbus port of your inverter. Default is '502'
modbus_slave: 1  # Update with the slave address of your inverter. Default is '1', start with '85' for AlphaESS, '247' for GoodWe, and '1' for others.
